### ISSUE TITLE
Enhancement suggestion: Fixed location for snippets

### ISSUE THREAD

**Issue by adxsoft** [Leleat/AGodotCodeSnippetPlugin#4]
The CodeSnippetPopup.cfg file contains the snippets. 

In order to always have the latest snippets in each project you need a master copy of CodeSnippetPopup.cfg that you manually copy into each new project.

It would be a good idea to have a **setting** for a location of the snippets file. In this way you can have only ONE external snippets file rather than lots of copies strewn about all the projects. Also you can keep the external snippets file under proper version control.

Let me know what you think.

PS. I have modified the plugin for my own use to point to a single external snippets file (snippet_config variable changed) and it manages all the snippets in one place now.

**Comment by Leleat** [comment]
Sounds good, I'll add it. 

I think the parent directory of the current project (i.e. the  directory where Godot stores all Projects) should do it. What do you think/What location did you use?

**Comment by adxsoft** [comment]
I agree 'the directory where Godot stores all Projects' is a good location. Thats effectively what I hacked for myself.
I'm still a Godot Noob so I'm not sure about tweaking the settings screen so I'll leave that to you :-)

**Comment by adxsoft** [comment]
Just to let you know I changed the following code to fix the location of my snippets

TextEditPopupPanel.gd

const snippet_config = "res://addons/CodeSnippetPopup/CodeSnippets.cfg"
to
const snippet_config = "/Users/allandavies/Developer/Godot/Snippets/MySnippets.txt”

CodeSnippetPopup.gd

const snippet_config = "res://addons/CodeSnippetPopup/CodeSnippets.cfg"
to
const snippet_config = "/Users/allandavies/Developer/Godot/Snippets/MySnippets.txt”

in function _update_snippets()
var error = file.load(res://addons/CodeSnippetPopup/CodeSnippets.cfg)
var error = file.load(snippet_config)

Cheers
Allan @ adxsoft
